import React, { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { RefreshCw, Languages } from 'lucide-react';

interface DynamicTextProps {
  originalText: string;
  className?: string;
  as?: any;
  key?: any;
  buttonClassName?: string;
}

export default function DynamicText({ originalText, className = "", as: Component = "div", buttonClassName = "mt-1" }: DynamicTextProps) {
  const { i18n, t } = useTranslation();
  const [translations, setTranslations] = useState<Record<string, string>>({});
  const [isTranslating, setIsTranslating] = useState(false);
  const [showTranslation, setShowTranslation] = useState(false);
  const [currentLang, setCurrentLang] = useState(i18n.language);

  // When language changes, we don't automatically translate anymore, per requirements:
  // "Dynamic content generated by users, AI, or the database should remain in its original language by default."
  // "When the user clicks Translate, translate only that specific content into the language currently selected"
  useEffect(() => {
    if (i18n.language !== currentLang) {
      setCurrentLang(i18n.language);
      setShowTranslation(false); // Reset to original if dashboard lang changes
    }
  }, [i18n.language, currentLang]);

  const fetchTranslation = async (lang: string) => {
    if (!originalText || !originalText.trim()) return;
    setIsTranslating(true);
    try {
      const response = await fetch('/api/translate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          texts: [originalText],
          targetLanguage: lang
        })
      });
      const data = await response.json();
      if (data.success && data.translations?.length > 0) {
        setTranslations(prev => ({ ...prev, [lang]: data.translations[0] }));
        setShowTranslation(true);
      }
    } catch (e) {
      console.error("Translation failed", e);
    } finally {
      setIsTranslating(false);
    }
  };

  const handleTranslate = async (e: React.MouseEvent) => {
    e.stopPropagation();
    e.preventDefault();
    if (showTranslation) {
      setShowTranslation(false);
      return;
    }
    
    if (translations[i18n.language]) {
      setShowTranslation(true);
      return;
    }

    await fetchTranslation(i18n.language);
  };

  return (
    <div className="relative group inline-block w-full">
      <Component className={className}>
        {showTranslation && translations[i18n.language] ? translations[i18n.language] : originalText}
      </Component>
      <div className={`flex items-center ${buttonClassName}`}>
        <button 
          type="button"
          onClick={handleTranslate}
          disabled={isTranslating}
          className="inline-flex items-center gap-1 text-[11px] font-medium text-[#1A237E] bg-[#E8EAF6] hover:bg-[#C5CAE9] px-2 py-0.5 rounded transition disabled:opacity-50"
          title={String(t("translate_dynamic"))}
        >
          {isTranslating ? (
            <><RefreshCw className="w-3 h-3 animate-spin" /> {String(t("submitting") || "Translating...")}</>
          ) : (
            <><Languages className="w-3 h-3" /> {showTranslation ? String(t("original_text")) : String(t("translate"))}</>
          )}
        </button>
      </div>
    </div>
  );
}
