// Dynamic timestamp helper to calculate past times relative to "now"
const hoursAgo = (h: number) => {
  return new Date(Date.now() - h * 60 * 60 * 1000).toISOString();
};

export const mockComplaints = [
  // COMPLAINTS 1-8: DARRANG DISTRICT (FLOOD + WATER + AGRICULTURE)
  {
    text_original: "আমাৰ গাঁৱৰ বান্ধ ভাঙি গৈছে। ব্ৰহ্মপুত্ৰৰ পানী পথাৰলৈ সোমাই আহিছে। খেতি নষ্ট হৈছে।",
    text_english: "Our village embankment has broken. Brahmaputra water is entering the fields. Crops are destroyed.",
    text_hindi: "हमारे गाँव का बाँध टूट गया है। ब्रह्मपुत्र का पानी खेतों में घुस रहा है। फसल बर्बाद हो गई है।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Agriculture",
    urgency: "Critical",
    issue_summary: "Embankment breach causing Brahmaputra flooding into agricultural fields destroying crops.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Darrang",
    district_hi: "दरांग",
    lok_sabha_en: "Darrang-Udalguri",
    lok_sabha_hi: "मंगलदोई",
    village: "Pub Dhansiri",
    panchayat: "Dhansiri Gaon Panchayat",
    police_station: "Khoirabari",
    pincode: "784116",
    latitude: 26.4521,
    longitude: 91.8734,
    anonymous: true,
    name: null,
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: true,
    theme_id: "brahmaputra_embankment_darrang",
    theme_name: "Brahmaputra Embankment Failure — Darrang",
    formatted_tracking_id: "JA-2026-MOCK0001",
    timestamp: hoursAgo(6 * 24 + 8),
    is_mock: true
  },
  {
    text_original: "চাৰি দিন ধৰি আমাৰ গাঁৱত পানী জমা হৈ আছে। ল'ৰা-ছোৱালীয়ে স্কুললৈ যাব পৰা নাই। ৰাস্তা ডুবি গৈছে।",
    text_english: "Water has been stagnant in our village for four days. Children cannot go to school. Roads are submerged.",
    text_hindi: "चार दिनों से हमारे गाँव में पानी जमा है। बच्चे स्कूल नहीं जा पा रहे। सड़क डूब गई है।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Roads",
    urgency: "Critical",
    issue_summary: "Village flooded for four days, roads submerged, children unable to attend school.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Darrang",
    district_hi: "दरांग",
    lok_sabha_en: "Darrang-Udalguri",
    lok_sabha_hi: "मंगलदोई",
    village: "Borbari",
    panchayat: "Borbari Gaon Panchayat",
    police_station: "Khoirabari",
    pincode: "784116",
    latitude: 26.4612,
    longitude: 91.8821,
    anonymous: false,
    name: "Rajen Kalita",
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: true,
    theme_id: "brahmaputra_embankment_darrang",
    theme_name: "Brahmaputra Embankment Failure — Darrang",
    formatted_tracking_id: "JA-2026-MOCK0002",
    timestamp: hoursAgo(6 * 24 + 10),
    is_mock: true
  },
  {
    text_original: "Embankment near Sipajhar broken since last week. Three villages under water. Need emergency relief immediately.",
    text_english: "Embankment near Sipajhar broken since last week. Three villages under water. Need emergency relief immediately.",
    text_hindi: "सिपाझार के पास बाँध पिछले हफ्ते से टूटा हुआ है। तीन गाँव पानी में डूबे हैं। तुरंत आपातकालीन राहत चाहिए।",
    language_detected: "English",
    language_native: "English",
    language_script: "Latin",
    category: "Agriculture",
    urgency: "Critical",
    issue_summary: "Embankment breach near Sipajhar submerging three villages requiring emergency relief.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Darrang",
    district_hi: "दरांग",
    lok_sabha_en: "Darrang-Udalguri",
    lok_sabha_hi: "मंगलदोई",
    village: "Sipajhar",
    panchayat: "Sipajhar Gaon Panchayat",
    police_station: "Sipajhar",
    pincode: "784145",
    latitude: 26.4834,
    longitude: 91.9123,
    anonymous: false,
    name: "Dipak Nath",
    phone: "9876543210",
    photo_url: "https://images.unsplash.com/photo-1547683905-f686c993aae5?w=400",
    photo_analysis: {
      what_is_shown: "Flooded agricultural fields with water level approximately 3 feet high, submerged crops visible",
      infrastructure_type: "Agricultural Land",
      damage_visible: true,
      damage_description: "Complete crop submersion, embankment breach visible in background",
      severity_from_photo: "Critical",
      severity_reasoning: "Entire field submerged indicating major embankment failure",
      safety_concern: true,
      safety_detail: "Rising water levels pose displacement risk to nearby residential areas",
      category_confirmed: true,
      category_suggested: null,
      estimated_affected_area: "District",
      flood_related: true,
      actionable_insight: "Emergency embankment repair and SDRF deployment required within 24 hours",
      confidence: 0.94,
      analyzed_at: hoursAgo(5 * 24),
      analysis_failed: false
    },
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "photo_analysis",
    safety_flagged: true,
    theme_id: "brahmaputra_embankment_darrang",
    theme_name: "Brahmaputra Embankment Failure — Darrang",
    formatted_tracking_id: "JA-2026-MOCK0003",
    timestamp: hoursAgo(5 * 24 + 7),
    is_mock: true
  },
  {
    text_original: "আমাৰ গাঁৱত খোৱাপানীৰ ব্যৱস্থা নাই। টিউবৱেলৰ পানী হালধীয়া হৈ গৈছে। ল'ৰা-ছোৱালী অসুস্থ হৈ পৰিছে।",
    text_english: "There is no drinking water arrangement in our village. Tubewell water has turned yellow. Children are falling sick.",
    text_hindi: "हमारे गाँव में पीने के पानी की व्यवस्था नहीं है। ट्यूबवेल का पानी पीला हो गया है। बच्चे बीमार पड़ रहे हैं।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Water Supply",
    urgency: "Critical",
    issue_summary: "Tubewell water contaminated yellow, no drinking water, children falling sick in village.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Darrang",
    district_hi: "दरांग",
    lok_sabha_en: "Darrang-Udalguri",
    lok_sabha_hi: "मंगलदोई",
    village: "Haribhanga",
    panchayat: "Haribhanga Gaon Panchayat",
    police_station: "Khoirabari",
    pincode: "784116",
    latitude: 26.4398,
    longitude: 91.8612,
    anonymous: true,
    name: null,
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "noted",
    mp_note: "Contacted PHE Department Assam for water quality testing. Field visit scheduled.",
    mp_note_timestamp: hoursAgo(3 * 24),
    mp_note_by: "MP Office",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "water_contamination_darrang",
    theme_name: "Water Contamination — Darrang",
    formatted_tracking_id: "JA-2026-MOCK0004",
    timestamp: hoursAgo(5 * 24 + 14),
    is_mock: true
  },
  {
    text_original: "আমাৰ পথাৰৰ ধান বানপানীত নষ্ট হৈ গ'ল। চৰকাৰী সাহায্য এতিয়াও পোৱা নাই। পৰিয়াল চলাবলৈ টকা নাই।",
    text_english: "Our paddy crop in the field was destroyed by flood. Government compensation not received yet. No money to run the family.",
    text_hindi: "हमारे खेत की धान बाढ़ में नष्ट हो गई। सरकारी मुआवज़ा अभी नहीं मिला। परिवार चलाने के लिए पैसे नहीं हैं।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Agriculture",
    urgency: "High",
    issue_summary: "Paddy crop destroyed by flood with no government compensation received yet.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Darrang",
    district_hi: "दरांग",
    lok_sabha_en: "Darrang-Udalguri",
    lok_sabha_hi: "मंगलदोई",
    village: "Kharupetia",
    panchayat: "Kharupetia Gaon Panchayat",
    police_station: "Kharupetia",
    pincode: "784115",
    latitude: 26.5123,
    longitude: 92.0234,
    anonymous: false,
    name: "Biren Das",
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "flood_crop_compensation",
    theme_name: "Flood Crop Loss — No Compensation",
    formatted_tracking_id: "JA-2026-MOCK0005",
    timestamp: hoursAgo(4 * 24 + 9),
    is_mock: true
  },
  {
    text_original: "বানপানীত আমাৰ গাঁৱৰ ৰাস্তা সম্পূৰ্ণৰূপে নষ্ট হৈ গৈছে। এম্বুলেন্স আহিব নোৱাৰে। এজন বৃদ্ধ মানুহ অসুস্থ।",
    text_english: "The road in our village is completely destroyed by flood. Ambulance cannot come. An elderly person is sick.",
    text_hindi: "बाढ़ में हमारे गाँव की सड़क पूरी तरह नष्ट हो गई है। एम्बुलेंस नहीं आ सकती। एक बुजुर्ग व्यक्ति बीमार है।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Roads",
    urgency: "Critical",
    issue_summary: "Flood-destroyed road blocking ambulance access while elderly patient needs medical care.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Darrang",
    district_hi: "दरांग",
    lok_sabha_en: "Darrang-Udalguri",
    lok_sabha_hi: "मंगलदोई",
    village: "Dalgaon",
    panchayat: "Dalgaon Gaon Panchayat",
    police_station: "Dalgaon",
    pincode: "784144",
    latitude: 26.4670,
    longitude: 92.0360,
    anonymous: false,
    name: "Manju Bora",
    phone: "8876543211",
    photo_url: null,
    photo_analysis: null,
    status: "escalated",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: true,
    theme_id: "flood_road_damage_darrang",
    theme_name: "Flood Road Damage — Darrang",
    formatted_tracking_id: "JA-2026-MOCK0006",
    timestamp: hoursAgo(3 * 24 + 6),
    is_mock: true
  },
  {
    text_original: "চাৰ এলেকাত পানী জমা হৈ থকাত মেলেৰিয়া বাঢ়িছে। স্বাস্থ্য কেন্দ্ৰত দৰব নাই। ডাক্তৰ আহে সপ্তাহত এবাৰ।",
    text_english: "Malaria spreading due to stagnant water in char areas. Health centre has no medicine. Doctor comes only once a week.",
    text_hindi: "चर इलाकों में पानी जमा होने से मलेरिया फैल रहा है। स्वास्थ्य केंद्र में दवाई नहीं है। डॉक्टर हफ्ते में एक बार आता है।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Healthcare",
    urgency: "Critical",
    issue_summary: "Malaria spreading in char areas due to flooding with inadequate medical facilities.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Darrang",
    district_hi: "दরাঙ্গ",
    lok_sabha_en: "Darrang-Udalguri",
    lok_sabha_hi: "मंग़लदै",
    village: "Char Kathalbari",
    panchayat: "Kathalbari Gaon Panchayat",
    police_station: "Khoirabari",
    pincode: "784116",
    latitude: 26.4156,
    longitude: 91.8234,
    anonymous: true,
    name: null,
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: true,
    theme_id: "healthcare_char_areas",
    theme_name: "Healthcare Crisis — Char Areas",
    formatted_tracking_id: "JA-2026-MOCK0007",
    timestamp: hoursAgo(2 * 24 + 11),
    is_mock: true
  },
  {
    text_original: "আমাৰ গাঁৱৰ স্কুলৰ ঘৰটো বানপানীত ভাঙি পৰিছে। ল'ৰা-ছোৱালীয়ে গছৰ তলত পঢ়িছে। পৰীক্ষা ওচৰ চাপিছে।",
    text_english: "School building in our village collapsed due to flood. Children are studying under trees. Exams are approaching.",
    text_hindi: "हमारे गाँव की स्कूल की इमारत बाढ़ में ढह गई है। बच्चे पेड़ के नीचे पढ़ रहे हैं। परीक्षाएं नज़दीक आ रही हैं।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Education/Schools",
    urgency: "High",
    issue_summary: "School building collapsed in flood, students studying under trees with exams approaching.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Darrang",
    district_hi: "दरांग",
    lok_sabha_en: "Darrang-Udalguri",
    lok_sabha_hi: "मंगलदोई",
    village: "Pub Salmara",
    panchayat: "Salmara Gaon Panchayat",
    police_station: "Sipajhar",
    pincode: "784145",
    latitude: 26.4723,
    longitude: 91.9345,
    anonymous: false,
    name: "Prafulla Deka",
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "school_flood_damage",
    theme_name: "School Infrastructure Damage — Flood",
    formatted_tracking_id: "JA-2026-MOCK0008",
    timestamp: hoursAgo(1 * 24 + 8),
    is_mock: true
  },

  // COMPLAINTS 9-16: BARPETA DISTRICT (FLOOD + EDUCATION + HEALTHCARE)
  {
    text_original: "বৰপেটাৰ চাৰ অঞ্চলত বানপানীয়ে বিধ্বংস কৰিছে। ৫০০ পৰিয়াল গৃহহাৰা হৈছে। ত্ৰাণ সামগ্ৰী এতিয়াও আহা নাই।",
    text_english: "Flood has devastated char areas of Barpeta. 500 families have lost their homes. Relief materials have not arrived yet.",
    text_hindi: "बारपेटा के चर क्षेत्रों में बाढ़ ने तबाही मचाई है। 500 परिवार बेघर हो गए हैं। राहत सामग्री अभी तक नहीं आई।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Other Issues",
    urgency: "Critical",
    issue_summary: "500 families displaced by flood in Barpeta char areas with no relief materials received.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Barpeta",
    district_hi: "बारपेटा",
    lok_sabha_en: "Barpeta",
    lok_sabha_hi: "बारपेटा",
    village: "Char Chapori",
    panchayat: "Chapori Gaon Panchayat",
    police_station: "Barpeta Road",
    pincode: "781315",
    latitude: 26.3234,
    longitude: 90.9876,
    anonymous: false,
    name: "Abdul Matin",
    phone: "7896541230",
    photo_url: "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=400",
    photo_analysis: {
      what_is_shown: "Flooded village with submerged houses and displaced families on elevated ground",
      infrastructure_type: "Residential Area",
      damage_visible: true,
      damage_description: "Multiple houses submerged to roof level, temporary shelters visible",
      severity_from_photo: "Critical",
      severity_reasoning: "Mass displacement evident from photo, immediate humanitarian crisis",
      safety_concern: true,
      safety_detail: "Families stranded without food, water or medical access",
      category_confirmed: false,
      category_suggested: "Other Issues",
      estimated_affected_area: "District",
      flood_related: true,
      actionable_insight: "Immediate NDRF/SDRF deployment and relief camp establishment required",
      confidence: 0.96,
      analyzed_at: hoursAgo(6 * 24),
      analysis_failed: false
    },
    status: "escalated",
    moderation_flag: "clean",
    urgency_source: "photo_analysis",
    safety_flagged: true,
    theme_id: "flood_displacement_barpeta",
    theme_name: "Mass Flood Displacement — Barpeta",
    formatted_tracking_id: "JA-2026-MOCK0009",
    timestamp: hoursAgo(6 * 24 + 6),
    is_mock: true
  },
  {
    text_original: "আমাদের স্কুলের শিক্ষক তিন মাস ধরে আসছেন না। परीक्षा आगे आ रही है। बच्चों की पढ़ाई नुकसान हो रही है।",
    text_english: "Our school teacher has not come for three months. Exams are approaching. Children's studies are being ruined.",
    text_hindi: "हमारे स्कूल के शिक्षक तीन महीने से नहीं आ रहे। परीक्षाएं नज़दीक हैं। बच्चों की पढ़ाई बर्बाद हो रही है।",
    language_detected: "Bengali",
    language_native: "বাংলা",
    language_script: "Bengali",
    category: "Education/Schools",
    urgency: "High",
    issue_summary: "School teacher absent for three months affecting students with upcoming exams.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Barpeta",
    district_hi: "बारपेटा",
    lok_sabha_en: "Barpeta",
    lok_sabha_hi: "बारपेटा",
    village: "Sarthebari",
    panchayat: "Sarthebari Gaon Panchayat",
    police_station: "Sarthebari",
    pincode: "781307",
    latitude: 26.3456,
    longitude: 91.0234,
    anonymous: false,
    name: "Sahida Begum",
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "teacher_absence_barpeta",
    theme_name: "Teacher Absence — Barpeta Schools",
    formatted_tracking_id: "JA-2026-MOCK0010",
    timestamp: hoursAgo(5 * 24 + 13),
    is_mock: true
  },
  {
    text_original: "আমাদের এলাকায় কোনো হাসপাতাল নেই। প্রসূতি মহিলাকে ৪০ কিলোমিটার দূরে নিয়ে যেতে হয়। রাস্তা খারাপ থাকায় বিপদ হয়।",
    text_english: "There is no hospital in our area. Pregnant women have to be taken 40 km away. Bad roads make it dangerous.",
    text_hindi: "हमारे इलाके में कोई अस्पताल नहीं है। गर्भवती महिलाओं को 40 किमी दूर ले जाना पड़ता है। खराब सड़क के कारण खतरा है।",
    language_detected: "Bengali",
    language_native: "বাংলা",
    language_script: "Bengali",
    category: "Healthcare",
    urgency: "Critical",
    issue_summary: "No hospital in area forces pregnant women to travel 40km on dangerous roads for delivery.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Barpeta",
    district_hi: "बारपेटा",
    lok_sabha_en: "Barpeta",
    lok_sabha_hi: "बारपेटा",
    village: "Mandia",
    panchayat: "Mandia Gaon Panchayat",
    police_station: "Mandia",
    pincode: "781352",
    latitude: 26.2987,
    longitude: 90.9123,
    anonymous: false,
    name: "Rahim Ali",
    phone: "9435123456",
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: true,
    theme_id: "maternal_health_barpeta",
    theme_name: "Maternal Healthcare Crisis — Barpeta",
    formatted_tracking_id: "JA-2026-MOCK0011",
    timestamp: hoursAgo(4 * 24 + 16),
    is_mock: true
  },
  {
    text_original: "Barpeta Road to Howly highway has 23 potholes in 5 km stretch. Two accidents happened last week. Nobody is repairing it.",
    text_english: "Barpeta Road to Howly highway has 23 potholes in 5 km stretch. Two accidents happened last week. Nobody is repairing it.",
    text_hindi: "बारपेटा रोड से होवली हाईवे पर 5 किमी में 23 गड्ढे हैं। पिछले हफ्ते दो दुर्घटनाएं हुईं। कोई मरम्मत नहीं कर रहा।",
    language_detected: "English",
    language_native: "English",
    language_script: "Latin",
    category: "Roads",
    urgency: "High",
    issue_summary: "23 potholes in 5km highway stretch caused two accidents last week with no repairs.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Barpeta",
    district_hi: "बारपेटा",
    lok_sabha_en: "Barpeta",
    lok_sabha_hi: "बारपेटा",
    village: "Howly",
    panchayat: "Howly Gaon Panchayat",
    police_station: "Howly",
    pincode: "781316",
    latitude: 26.4012,
    longitude: 90.8765,
    anonymous: false,
    name: "Pranab Sarma",
    phone: "8638234567",
    photo_url: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=400",
    photo_analysis: {
      what_is_shown: "Damaged road surface with multiple large potholes, vehicle visible navigating around them",
      infrastructure_type: "Road",
      damage_visible: true,
      damage_description: "Multiple severe potholes across entire road width, surface completely degraded",
      severity_from_photo: "High",
      severity_reasoning: "Extensive pothole damage creating significant traffic hazard",
      safety_concern: true,
      safety_detail: "Road condition poses collision risk especially for two-wheelers at night",
      category_confirmed: true,
      category_suggested: null,
      estimated_affected_area: "Block",
      flood_related: false,
      actionable_insight: "PWD Assam emergency road repair request for Barpeta Road-Howly stretch",
      confidence: 0.91,
      analyzed_at: hoursAgo(4 * 24),
      analysis_failed: false
    },
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "photo_analysis",
    safety_flagged: true,
    theme_id: "road_damage_barpeta",
    theme_name: "Highway Damage — Barpeta-Howly",
    formatted_tracking_id: "JA-2026-MOCK0012",
    timestamp: hoursAgo(3 * 24 + 9),
    is_mock: true
  },
  {
    text_original: "আমাৰ গাঁৱত বিদ্যুৎ নাই তিনি মাহ হ'ল। ট্ৰেন্সফৰ্মাৰ জ্বলি গৈছে। ছাত্ৰ-ছাত্ৰীসকলে পঢ়িব পৰা নাই।",
    text_english: "Our village has had no electricity for three months. Transformer has burnt out. Students cannot study.",
    text_hindi: "हमारे गाँव में तीन महीने से बिजली नहीं है। ट्रांसफॉर्मर जल गया है। छात्र पढ़ नहीं पा रहे।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Electricity",
    urgency: "High",
    issue_summary: "Village without electricity for three months after transformer burnout affecting students.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Barpeta",
    district_hi: "बारपेटा",
    lok_sabha_en: "Barpeta",
    lok_sabha_hi: "बारपेटा",
    village: "Bajali",
    panchayat: "Bajali Gaon Panchayat",
    police_station: "Bajali",
    pincode: "781325",
    latitude: 26.4678,
    longitude: 91.1234,
    anonymous: true,
    name: null,
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "electricity_outage_barpeta",
    theme_name: "Electricity Outage — Barpeta",
    formatted_tracking_id: "JA-2026-MOCK0013",
    timestamp: hoursAgo(2 * 24 + 15),
    is_mock: true
  },
  {
    text_original: "আমাদের গ্রামে পানীয় জলের কোনো ব্যবস্থা নেই। পুকুরের পানি পান করতে হচ্ছে। অনেকে অসুস্থ হয়ে পড়েছে।",
    text_english: "There is no drinking water arrangement in our village. We have to drink pond water. Many people have fallen sick.",
    text_hindi: "हमारे गाँव में पीने के पानी का कोई इंतजाम नहीं है। तालाब का पानी पीना पड़ रहा है। बहुत लोग बीमार पड़ गए हैं।",
    language_detected: "Bengali",
    language_native: "বাংলা",
    language_script: "Bengali",
    category: "Water Supply",
    urgency: "Critical",
    issue_summary: "No drinking water forcing villagers to drink pond water causing widespread illness.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Barpeta",
    district_hi: "बारपेटा",
    lok_sabha_en: "Barpeta",
    lok_sabha_hi: "बारपेटा",
    village: "Chenga",
    panchayat: "Chenga Gaon Panchayat",
    police_station: "Chenga",
    pincode: "781127",
    latitude: 26.2345,
    longitude: 90.7654,
    anonymous: false,
    name: "Fatema Khatun",
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "water_contamination_darrang",
    theme_name: "Water Contamination — Darrang",
    formatted_tracking_id: "JA-2026-MOCK0014",
    timestamp: hoursAgo(1 * 24 + 10),
    is_mock: true
  },
  {
    text_original: "বানপানীৰ পিছত আমাৰ গাঁৱত চেনিটেশ্বনৰ অৱস্থা বেয়া। শৌচালয় ভাঙি গৈছে। ৰোগ বিয়পাৰ ভয় আছে।",
    text_english: "After flood, sanitation situation in our village is bad. Toilets are damaged. Fear of disease spreading.",
    text_hindi: "बाढ़ के बाद हमारे गाँव में स्वच्छता की स्थिति खराब है। शौचालय टूट गए हैं। बीमारी फैलने का डर है।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Sanitation/Waste",
    urgency: "High",
    issue_summary: "Post-flood sanitation crisis with damaged toilets raising disease outbreak fears.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Barpeta",
    district_hi: "बारपेटा",
    lok_sabha_en: "Barpeta",
    lok_sabha_hi: "बारपेटा",
    village: "Bhabanipur",
    panchayat: "Bhabanipur Gaon Panchayat",
    police_station: "Bhabanipur",
    pincode: "781352",
    latitude: 26.3789,
    longitude: 90.9456,
    anonymous: true,
    name: null,
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "post_flood_sanitation",
    theme_name: "Post-Flood Sanitation Crisis",
    formatted_tracking_id: "JA-2026-MOCK0015",
    timestamp: hoursAgo(1 * 24 + 14),
    is_mock: true
  },
  {
    text_original: "Anganwadi centre in our village has been closed for 2 months. Children below 6 years not getting nutrition. No explanation given.",
    text_english: "Anganwadi centre in our village has been closed for 2 months. Children below 6 years not getting nutrition. No explanation given.",
    text_hindi: "हमारे गाँव का आंगनवाड़ी केंद्र 2 महीने से बंद है। 6 साल से कम उम्र के बच्चों को पोषण नहीं मिल रहा। कोई स्पष्टीकरण नहीं।",
    language_detected: "English",
    language_native: "English",
    language_script: "Latin",
    category: "Healthcare",
    urgency: "High",
    issue_summary: "Anganwadi centre closed for 2 months leaving children under 6 without nutrition support.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Barpeta",
    district_hi: "बारपेटा",
    lok_sabha_en: "Barpeta",
    lok_sabha_hi: "बारपेटा",
    village: "Sarupeta",
    panchayat: "Sarupeta Gaon Panchayat",
    police_station: "Sarupeta",
    pincode: "781127",
    latitude: 26.1567,
    longitude: 90.8234,
    anonymous: false,
    name: "Minakshi Das",
    phone: "9706123456",
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "anganwadi_closure",
    theme_name: "Anganwadi Closure — Nutrition Crisis",
    formatted_tracking_id: "JA-2026-MOCK0016",
    timestamp: hoursAgo(7),
    is_mock: true
  },

  // COMPLAINTS 17-24: DIBRUGARH DISTRICT (TEA GARDEN + HEALTHCARE + ROADS)
  {
    text_original: "চাহ বাগিচাৰ হাস্পতালত ডাক্তৰ নাই তিনি মাহ হ'ল। শ্ৰমিকসকলে গুৱাহাটীলৈ যাব লগা হৈছে। টকাও নাই।",
    text_english: "Tea garden hospital has had no doctor for three months. Workers have to go to Guwahati. No money either.",
    text_hindi: "चाय बागान अस्पताल में तीन महीने से डॉक्टर नहीं है। मज़दूरों को गुवाहाटी जाना पड़ रहा है। पैसे भी नहीं हैं।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Healthcare",
    urgency: "Critical",
    issue_summary: "Tea garden hospital without doctor for three months forcing workers to travel to Guwahati.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Dibrugarh",
    district_hi: "डिब्रूगढ़",
    lok_sabha_en: "Dibrugarh",
    lok_sabha_hi: "डिब्रूगढ़",
    village: "Naharkatia",
    panchayat: "Naharkatia Tea Garden",
    police_station: "Naharkatia",
    pincode: "786610",
    latitude: 27.2876,
    longitude: 95.3456,
    anonymous: false,
    name: "Lakshmi Orang",
    phone: "8135456789",
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: true,
    theme_id: "tea_garden_healthcare",
    theme_name: "Tea Garden Healthcare Crisis — Dibrugarh",
    formatted_tracking_id: "JA-2026-MOCK0017",
    timestamp: hoursAgo(6 * 24 + 7),
    is_mock: true
  },
  {
    text_original: "Tea garden workers' children school has no toilet for girls. Girls are dropping out. Management is not responding to complaints.",
    text_english: "Tea garden workers' children school has no toilet for girls. Girls are dropping out. Management is not responding to complaints.",
    text_hindi: "चाय बागान मज़दूरों के बच्चों के स्कूल में लड़कियों के लिए शौचालय नहीं है। लड़कियाँ स्कूल छोड़ रही हैं। प्रबंधन शिकायत पर ध्यान नहीं दे रहा।",
    language_detected: "English",
    language_native: "English",
    language_script: "Latin",
    category: "Education/Schools",
    urgency: "High",
    issue_summary: "Tea garden school lacks girls' toilet causing female student dropout with unresponsive management.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Dibrugarh",
    district_hi: "डिब्रूगढ़",
    lok_sabha_en: "Dibrugarh",
    lok_sabha_hi: "डिब्रूगढ़",
    village: "Digboi",
    panchayat: "Digboi Tea Garden",
    police_station: "Digboi",
    pincode: "786171",
    latitude: 27.3876,
    longitude: 95.6234,
    anonymous: false,
    name: "Sunita Tanti",
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "tea_garden_education",
    theme_name: "Tea Garden School Issues — Dibrugarh",
    formatted_tracking_id: "JA-2026-MOCK0018",
    timestamp: hoursAgo(5 * 24 + 11),
    is_mock: true
  },
  {
    text_original: "ডিব্ৰুগড়ৰ পথঘাট অতি বেয়া। বৰষুণৰ পিছত গাঁতেৰে ভৰি যায়। দুচকীয়া বাহন চলাব পৰা নহয়।",
    text_english: "Roads in Dibrugarh are very bad. After rain they fill with potholes. Two-wheelers cannot navigate.",
    text_hindi: "डिब्रूगढ़ की सड़कें बहुत खराब हैं। बारिश के बाद गड्ढों से भर जाती हैं। दोपहिया वाहन नहीं चला सकते।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Roads",
    urgency: "Medium",
    issue_summary: "Poor road conditions in Dibrugarh fill with potholes after rain making two-wheelers unsafe.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Dibrugarh",
    district_hi: "डिब्रूगढ़",
    lok_sabha_en: "Dibrugarh",
    lok_sabha_hi: "डिब्रूगढ़",
    village: "Moran",
    panchayat: "Moran Gaon Panchayat",
    police_station: "Moran",
    pincode: "785670",
    latitude: 27.1654,
    longitude: 95.1876,
    anonymous: true,
    name: null,
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "resolved",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "road_damage_dibrugarh",
    theme_name: "Road Damage — Dibrugarh",
    formatted_tracking_id: "JA-2026-MOCK0019",
    timestamp: hoursAgo(4 * 24 + 12),
    is_mock: true
  },
  {
    text_original: "চাহ শ্ৰমিকসকলৰ মজুৰি তিনি মাহ ধৰি বকেয়া আছে। বাগিচা কৰ্তৃপক্ষ উত্তৰ নিদিয়ে। পৰিয়াল খাব পৰা নাই।",
    text_english: "Tea workers' wages are pending for three months. Garden management not responding. Family cannot eat.",
    text_hindi: "चाय मज़दूरों की तीन महीने की मज़दूरी बकाया है। बागान प्रबंधन जवाब नहीं दे रहा। परिवार खाना नहीं खा पा रहा।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Other Issues",
    urgency: "High",
    issue_summary: "Tea workers' wages unpaid for three months with unresponsive management causing food insecurity.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Dibrugarh",
    district_hi: "डिब्रूगढ़",
    lok_sabha_en: "Dibrugarh",
    lok_sabha_hi: "डिब्रूगढ़",
    village: "Chabua",
    panchayat: "Chabua Tea Garden",
    police_station: "Chabua",
    pincode: "786184",
    latitude: 27.4567,
    longitude: 95.1234,
    anonymous: false,
    name: "Mangal Munda",
    phone: "9435987654",
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "tea_worker_wages",
    theme_name: "Tea Worker Wage Delay — Dibrugarh",
    formatted_tracking_id: "JA-2026-MOCK0020",
    timestamp: hoursAgo(3 * 24 + 8),
    is_mock: true
  },
  {
    text_original: "আমাৰ চাহ বাগিচাৰ স্কুলত শিক্ষক নাই। চৰকাৰী শিক্ষক নিযুক্ত হোৱা নাই। ল'ৰা-ছোৱালী বঞ্চিত হৈছে।",
    text_english: "Our tea garden school has no teacher. Government teacher not appointed. Children are being deprived.",
    text_hindi: "हमारे चाय बागान के स्कूल में शिक्षक नहीं है। सरकारी शिक्षक नियुक्त नहीं हुआ। बच्चे वंचित हो रहे हैं।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Education/Schools",
    urgency: "High",
    issue_summary: "Tea garden school without government-appointed teacher leaving children without education.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Dibrugarh",
    district_hi: "डिब्रूगढ़",
    lok_sabha_en: "Dibrugarh",
    lok_sabha_hi: "डिब्रूगढ़",
    village: "Lahoal",
    panchayat: "Lahoal Tea Garden",
    police_station: "Lahoal",
    pincode: "786010",
    latitude: 27.3234,
    longitude: 94.9876,
    anonymous: true,
    name: null,
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "tea_garden_education",
    theme_name: "Tea Garden School Issues — Dibrugarh",
    formatted_tracking_id: "JA-2026-MOCK0021",
    timestamp: hoursAgo(2 * 24 + 9),
    is_mock: true
  },
  {
    text_original: "Dibrugarh civil hospital blood bank is empty. Patient needs blood transfusion urgently. No blood available anywhere nearby.",
    text_english: "Dibrugarh civil hospital blood bank is empty. Patient needs blood transfusion urgently. No blood available anywhere nearby.",
    text_hindi: "डिब्रूगढ़ सिविल अस्पताल का ब्लड बैंक खाली है। मरीज़ को तुरंत रक्त आधान की ज़रूरत है। पास में कहीं खून नहीं मिल रहा।",
    language_detected: "English",
    language_native: "English",
    language_script: "Latin",
    category: "Healthcare",
    urgency: "Critical",
    issue_summary: "Civil hospital blood bank empty leaving patient without urgently needed blood transfusion.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Dibrugarh",
    district_hi: "डिब्रूगढ़",
    lok_sabha_en: "Dibrugarh",
    lok_sabha_hi: "डिब्रूगढ़",
    village: "Dibrugarh Town",
    panchayat: "Dibrugarh Municipal",
    police_station: "Dibrugarh",
    pincode: "786001",
    latitude: 27.4728,
    longitude: 94.9120,
    anonymous: false,
    name: "Dr. Pranjal Gogoi",
    phone: "9954123456",
    photo_url: null,
    photo_analysis: null,
    status: "escalated",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: true,
    theme_id: "tea_garden_healthcare",
    theme_name: "Tea Garden Healthcare Crisis — Dibrugarh",
    formatted_tracking_id: "JA-2026-MOCK0022",
    timestamp: hoursAgo(1 * 24 + 6),
    is_mock: true
  },
  {
    text_original: "আমাৰ এলেকাত PMAY ঘৰ পোৱা নাই যদিও তালিকাত নাম আছে। দুৰ্নীতি হৈছে বুলি শুনিছো। কোনে সহায় কৰিব?",
    text_english: "PMAY house not received despite name being on the list. Heard there is corruption. Who will help?",
    text_hindi: "नाम सूची में होने के बावजूद PMAY घर नहीं मिला। भ्रष्टाचार हो रहा है ऐसा सुना है। कौन मदद करेगा?",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Other Issues",
    urgency: "Medium",
    issue_summary: "PMAY house not received despite being on beneficiary list with suspected corruption.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Dibrugarh",
    district_hi: "डिब्रूगढ़",
    lok_sabha_en: "Dibrugarh",
    lok_sabha_hi: "डिब्रूगढ़",
    village: "Barbaruah",
    panchayat: "Barbaruah Gaon Panchayat",
    police_station: "Barbaruah",
    pincode: "786125",
    latitude: 27.3456,
    longitude: 95.0567,
    anonymous: true,
    name: null,
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "scheme_corruption",
    theme_name: "Government Scheme Irregularities",
    formatted_tracking_id: "JA-2026-MOCK0023",
    timestamp: hoursAgo(12),
    is_mock: true
  },
  {
    text_original: "চাহ বাগিচাৰ মহিলা শ্ৰমিকসকলে নিৰাপদ পানী পোৱা নাই। বাগিচাৰ নলা-নৰ্দমা উন্মুক্ত। ৰোগ বিয়পিছে।",
    text_english: "Female tea garden workers do not have access to safe water. Garden drains are open. Disease is spreading.",
    text_hindi: "महिला चाय बागान मज़दूरों को सुरक्षित पानी नहीं मिल रहा। बागान की नालियाँ खुली हैं। बीमारी फैल रही है।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Water Supply",
    urgency: "High",
    issue_summary: "Female tea workers lack safe water with open drains spreading disease in garden area.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Dibrugarh",
    district_hi: "डिब्रूगढ़",
    lok_sabha_en: "Dibrugarh",
    lok_sabha_hi: "ডিগবৈ",
    village: "Tingkhong",
    panchayat: "Tingkhong Tea Garden",
    police_station: "Tingkhong",
    pincode: "786612",
    latitude: 27.2123,
    longitude: 95.0234,
    anonymous: false,
    name: "Parbati Gowala",
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "tea_garden_healthcare",
    theme_name: "Tea Garden Healthcare Crisis — Dibrugarh",
    formatted_tracking_id: "JA-2026-MOCK0024",
    timestamp: hoursAgo(5),
    is_mock: true
  },

  // COMPLAINTS 25-32: NAGAON DISTRICT (ROADS + WATER + AGRICULTURE)
  {
    text_original: "নগাঁৱৰ ৰাষ্ট্ৰীয় ঘাইপথ ৩৬ত বানপানীৰ ফলত বিশাল গাঁত হৈছে। পণ্যবাহী ট্ৰাক উলটি গৈছে। দ্ৰুত মেৰামতি দৰকাৰ।",
    text_english: "National Highway 36 in Nagaon has huge potholes due to flood. Goods truck overturned. Urgent repair needed.",
    text_hindi: "नागाँव में राष्ट्रीय राजमार्ग 36 पर बाढ़ से विशाल गड्ढे हो गए हैं। माल ट्रक पलट गया है। तत्काल मरम्मत जरूरी है।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Roads",
    urgency: "Critical",
    issue_summary: "NH-36 Nagaon damaged by flood causing truck overturn requiring urgent repair.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Nagaon",
    district_hi: "नागाँव",
    lok_sabha_en: "Nagaon",
    lok_sabha_hi: "नागाँव",
    village: "Kampur",
    panchayat: "Kampur Gaon Panchayat",
    police_station: "Kampur",
    pincode: "782410",
    latitude: 26.2456,
    longitude: 92.6789,
    anonymous: false,
    name: "Bhupen Saikia",
    phone: "9435765432",
    photo_url: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=400",
    photo_analysis: {
      what_is_shown: "Highway with severe flood damage, large section of road washed away, overturned vehicle visible",
      infrastructure_type: "Road",
      damage_visible: true,
      damage_description: "Major road section washed away by flood, structural failure of road base",
      severity_from_photo: "Critical",
      severity_reasoning: "Road collapse causing vehicle accidents indicating immediate safety emergency",
      safety_concern: true,
      safety_detail: "Overturned vehicle and collapsed road pose life-threatening risk to travelers",
      category_confirmed: true,
      category_suggested: null,
      estimated_affected_area: "District",
      flood_related: true,
      actionable_insight: "Immediate NHIDCL/PWD emergency repair and traffic diversion required",
      confidence: 0.95,
      analyzed_at: hoursAgo(5 * 24),
      analysis_failed: false
    },
    status: "escalated",
    moderation_flag: "clean",
    urgency_source: "photo_analysis",
    safety_flagged: true,
    theme_id: "highway_flood_damage_nagaon",
    theme_name: "NH-36 Flood Damage — Nagaon",
    formatted_tracking_id: "JA-2026-MOCK0025",
    timestamp: hoursAgo(5 * 24 + 8),
    is_mock: true
  },
  {
    text_original: "নগাঁৱত বৰষুণৰ পানী জমা হৈ মছা বাঢ়িছে। ডেংগু হোৱাৰ খবৰ আহিছে। স্বাস্থ্য বিভাগে ব্যৱস্থা লোৱা নাই।",
    text_english: "Rainwater stagnating in Nagaon increasing mosquitoes. Reports of dengue fever coming. Health department has not taken action.",
    text_hindi: "नागाँव में बारिश का पानी जमा होने से मच्छर बढ़ रहे हैं। डेंगू बुखार की खबरें आ रही हैं। स्वास्थ्य विभाग ने कार्रवाई नहीं की।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Healthcare",
    urgency: "High",
    issue_summary: "Stagnant rainwater causing mosquito breeding and dengue fever reports in Nagaon.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Nagaon",
    district_hi: "नागाँव",
    lok_sabha_en: "Nagaon",
    lok_sabha_hi: "नागाँव",
    village: "Hojai",
    panchayat: "Hojai Municipal",
    police_station: "Hojai",
    pincode: "782435",
    latitude: 26.0023,
    longitude: 92.8567,
    anonymous: false,
    name: "Nilufar Hussain",
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "vector_disease_nagaon",
    theme_name: "Vector-Borne Disease Risk — Nagaon",
    formatted_tracking_id: "JA-2026-MOCK0026",
    timestamp: hoursAgo(4 * 24 + 10),
    is_mock: true
  },
  {
    text_original: "আমার গ্রামের কৃষকরা সার পাচ্ছেন না। দোকানে সার নেই। বীজ বপনের সময় পেরিয়ে যাচ্ছে।",
    text_english: "Farmers in our village are not getting fertilizer. No fertilizer in shops. Sowing season is passing.",
    text_hindi: "हमारे गाँव के किसानों को उर्वरक नहीं मिल रहा। दुकान में खाद नहीं है। बुवाई का समय निकला जा रहा है।",
    language_detected: "Bengali",
    language_native: "বাংলা",
    language_script: "Bengali",
    category: "Agriculture",
    urgency: "High",
    issue_summary: "Fertilizer shortage during sowing season threatening crop planting for Nagaon farmers.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Nagaon",
    district_hi: "नागाँव",
    lok_sabha_en: "Nagaon",
    lok_sabha_hi: "नागाँव",
    village: "Raha",
    panchayat: "Raha Gaon Panchayat",
    police_station: "Raha",
    pincode: "782103",
    latitude: 26.1789,
    longitude: 92.5234,
    anonymous: false,
    name: "Hafizur Rahman",
    phone: "8638765432",
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "fertilizer_shortage",
    theme_name: "Fertilizer Shortage — Nagaon Farmers",
    formatted_tracking_id: "JA-2026-MOCK0027",
    timestamp: hoursAgo(3 * 24 + 11),
    is_mock: true
  },
  {
    text_original: "নগাঁৱৰ কপিলী নদীৰ গৰাখহনীয়াই বহু পৰিয়ালৰ ঘৰ-মাটি নিছে। ক্ষতিপূৰণ পোৱা নাই।",
    text_english: "River erosion from Kopili river in Nagaon has taken away homes and land of many families. No compensation received.",
    text_hindi: "नागाँव में कपिली नदी के कटाव से कई परिवारों के घर और जमीन बह गई है। मुआवज़ा नहीं मिला।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Other Issues",
    urgency: "High",
    issue_summary: "Kopili river erosion destroying homes and land with no compensation for affected families.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Nagaon",
    district_hi: "नागाँव",
    lok_sabha_en: "Nagaon",
    lok_sabha_hi: "नागाँव",
    village: "Samaguri",
    panchayat: "Samaguri Gaon Panchayat",
    police_station: "Samaguri",
    pincode: "782141",
    latitude: 26.3234,
    longitude: 92.4567,
    anonymous: false,
    name: "Dimbeswar Deka",
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "river_erosion_assam",
    theme_name: "River Erosion — Kopili Nagaon",
    formatted_tracking_id: "JA-2026-MOCK0028",
    timestamp: hoursAgo(2 * 24 + 13),
    is_mock: true
  },
  {
    text_original: "আমাৰ গাঁৱত মধ্যাহ্ন ভোজন বন্ধ হৈ গৈছে। ল'ৰা-ছোৱালীয়ে খাদ্য নাপায়। চৰকাৰী পুঁজি আহিছে বুলি জানো কিন্তু বিতৰণ হোৱা নাই।",
    text_english: "Mid-day meal has stopped in our village school. Children are not getting food. Government funds have come but not distributed.",
    text_hindi: "हमारे गाँव के स्कूल में मध्याह्न भोजन बंद हो गया है। बच्चों को खाना नहीं मिल रहा। सरकारी फंड आया है पर बांटा नहीं गया।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Education/Schools",
    urgency: "High",
    issue_summary: "School mid-day meal stopped despite government funds arriving leaving children without food.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Nagaon",
    district_hi: "नागाँव",
    lok_sabha_en: "Nagaon",
    lok_sabha_hi: "नागाँव",
    village: "Kaliabor",
    panchayat: "Kaliabor Gaon Panchayat",
    police_station: "Kaliabor",
    pincode: "782137",
    latitude: 26.4567,
    longitude: 93.0123,
    anonymous: false,
    name: "Gita Saikia",
    phone: "9706456789",
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "midday_meal_irregularity",
    theme_name: "Mid-Day Meal Irregularities",
    formatted_tracking_id: "JA-2026-MOCK0029",
    timestamp: hoursAgo(1 * 24 + 12),
    is_mock: true
  },
  {
    text_original: "Nagaon town drainage blocked. Streets flooded after every rain. Municipal corporation not cleaning drains for years.",
    text_english: "Nagaon town drainage blocked. Streets flooded after every rain. Municipal corporation not cleaning drains for years.",
    text_hindi: "नागाँव शहर की नालियाँ बंद हैं। हर बारिश के बाद सड़कें डूब जाती हैं। नगर निगम सालों से नालियाँ साफ नहीं कर रहा।",
    language_detected: "English",
    language_native: "English",
    language_script: "Latin",
    category: "Sanitation/Waste",
    urgency: "Medium",
    issue_summary: "Blocked town drainage causing street flooding after every rain due to years of neglect.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Nagaon",
    district_hi: "नागाँव",
    lok_sabha_en: "Nagaon",
    lok_sabha_hi: "नागाँव",
    village: "Nagaon Town",
    panchayat: "Nagaon Municipal",
    police_station: "Nagaon",
    pincode: "782001",
    latitude: 26.3478,
    longitude: 92.6834,
    anonymous: false,
    name: "Rupam Baruah",
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "urban_drainage_nagaon",
    theme_name: "Urban Drainage — Nagaon Town",
    formatted_tracking_id: "JA-2026-MOCK0030",
    timestamp: hoursAgo(9),
    is_mock: true
  },

  // COMPLAINTS 31-35: MAJULI DISTRICT (EROSION + CONNECTIVITY + CULTURE)
  {
    text_original: "মাজুলীৰ ব্ৰহ্মপুত্ৰৰ খহনীয়াই আমাৰ পৰিয়ালৰ মাটি নিলে। আমাৰ ঘৰ ভাঙিছে। ক'লৈ যাম জানো নাই।",
    text_english: "Brahmaputra erosion in Majuli has taken our family's land. Our house is broken. We do not know where to go.",
    text_hindi: "माजुली में ब्रह्मपुत्र के कटाव ने हमारे परिवार की जमीन ले ली। हमारा घर टूट गया है। नहीं पता कहाँ जाएं।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Other Issues",
    urgency: "Critical",
    issue_summary: "Brahmaputra erosion destroyed family home and land in Majuli with nowhere to relocate.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Majuli",
    district_hi: "माजुली",
    lok_sabha_en: "Jorhat",
    lok_sabha_hi: "जोरहाट",
    village: "Kamalabari",
    panchayat: "Kamalabari Gaon Panchayat",
    police_station: "Majuli",
    pincode: "785106",
    latitude: 26.9456,
    longitude: 94.1678,
    anonymous: false,
    name: "Suren Payeng",
    phone: "8134567890",
    photo_url: "https://images.unsplash.com/photo-1547683905-f686c993aae5?w=400",
    photo_analysis: {
      what_is_shown: "Riverbank collapsed with house partially fallen into water, severe erosion visible",
      infrastructure_type: "Residential Area",
      damage_visible: true,
      damage_description: "House structure collapsed into river due to severe bank erosion",
      severity_from_photo: "Critical",
      severity_reasoning: "Home completely lost to erosion indicating irreversible displacement",
      safety_concern: true,
      safety_detail: "Family in immediate danger of complete home loss and displacement",
      category_confirmed: true,
      category_suggested: null,
      estimated_affected_area: "Village",
      flood_related: true,
      actionable_insight: "Emergency relocation support and erosion protection measures required immediately",
      confidence: 0.93,
      analyzed_at: hoursAgo(6 * 24),
      analysis_failed: false
    },
    status: "escalated",
    moderation_flag: "clean",
    urgency_source: "photo_analysis",
    safety_flagged: true,
    theme_id: "majuli_erosion",
    theme_name: "Brahmaputra Erosion — Majuli Island",
    formatted_tracking_id: "JA-2026-MOCK0031",
    timestamp: hoursAgo(6 * 24 + 5),
    is_mock: true
  },
  {
    text_original: "মাজুলীৰ পৰা যাতায়তৰ একমাত্ৰ ভৰোসা নাওখন। ফেৰী সেৱা অনিয়মীয়া। অসুস্থ মানুহক নি নোৱাৰি।",
    text_english: "The only means of transport from Majuli is the boat. Ferry service is irregular. Cannot take sick people across.",
    text_hindi: "माजुली से आवाजाही का एकमात्र सहारा नाव है। फेरी सेवा अनियमित है। बीमार लोगों को नहीं ले जा सकते।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Roads",
    urgency: "High",
    issue_summary: "Irregular ferry service from Majuli island preventing medical evacuation of sick patients.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Majuli",
    district_hi: "माजुली",
    lok_sabha_en: "Jorhat",
    lok_sabha_hi: "जोरहाट",
    village: "Garamur",
    panchayat: "Garamur Gaon Panchayat",
    police_station: "Majuli",
    pincode: "785106",
    latitude: 26.9876,
    longitude: 94.2345,
    anonymous: true,
    name: null,
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: true,
    theme_id: "majuli_connectivity",
    theme_name: "Island Connectivity Crisis — Majuli",
    formatted_tracking_id: "JA-2026-MOCK0032",
    timestamp: hoursAgo(5 * 24 + 15),
    is_mock: true
  },
  {
    text_original: "মাজুলীৰ সত্ৰসমূহ সংস্কাৰৰ অভাৱত জৰাজীৰ্ণ হৈছে। পৰ্যটক আহে কিন্তু সুবিধা নাই। ঐতিহ্য ৰক্ষা কৰিব লাগিব।",
    text_english: "Satras of Majuli are dilapidated due to lack of renovation. Tourists come but no facilities. Heritage must be preserved.",
    text_hindi: "माजुली के सत्र नवीनीकरण के अभाव में जर्जर हो गए हैं। पर्यटक आते हैं लेकिन सुविधाएं नहीं हैं। विरासत बचानी होगी।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Other Issues",
    urgency: "Medium",
    issue_summary: "Historic Majuli Satras deteriorating from lack of renovation despite tourist interest.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Majuli",
    district_hi: "माजुली",
    lok_sabha_en: "Jorhat",
    lok_sabha_hi: "जोरहाट",
    village: "Auniati",
    panchayat: "Auniati Gaon Panchayat",
    police_station: "Majuli",
    pincode: "785106",
    latitude: 26.9234,
    longitude: 94.1234,
    anonymous: false,
    name: "Paramananda Deva Goswami",
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "majuli_heritage",
    theme_name: "Majuli Heritage Preservation",
    formatted_tracking_id: "JA-2026-MOCK0033",
    timestamp: hoursAgo(4 * 24 + 14),
    is_mock: true
  },
  {
    text_original: "মাজুলীত বিদ্যুৎ সংযোগ নাই বহু গাঁৱত। সৌৰ শক্তিৰ প্ৰতিশ্ৰুতি দিছিল কিন্তু আহা নাই। আন্ধাৰতে থাকো।",
    text_english: "Many villages in Majuli have no electricity connection. Solar power was promised but has not come. We live in darkness.",
    text_hindi: "माजुली के कई गाँवों में बिजली कनेक्शन नहीं है। सौर ऊर्जा का वादा था लेकिन आया नहीं। अंधेरे में रहते हैं।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Electricity",
    urgency: "High",
    issue_summary: "Multiple Majuli villages lack electricity with promised solar power not delivered.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Majuli",
    district_hi: "माजुली",
    lok_sabha_en: "Jorhat",
    lok_sabha_hi: "जोरहाट",
    village: "Bengenaati",
    panchayat: "Bengenaati Gaon Panchayat",
    police_station: "Majuli",
    pincode: "785106",
    latitude: 27.0123,
    longitude: 94.2789,
    anonymous: true,
    name: null,
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "majuli_connectivity",
    theme_name: "Island Connectivity Crisis — Majuli",
    formatted_tracking_id: "JA-2026-MOCK0034",
    timestamp: hoursAgo(3 * 24 + 16),
    is_mock: true
  },
  {
    text_original: "মাজুলীত মৎস্যজীৱীসকলৰ নাও বানপানীত উটি গৈছে। জীৱিকা নাইকিয়া হৈছে। ক্ষতিপূৰণ দাবী কৰিছো।",
    text_english: "Fishermen's boats in Majuli washed away in flood. Livelihood destroyed. Demanding compensation.",
    text_hindi: "माजुली में मछुआरों की नावें बाढ़ में बह गईं। आजीविका नष्ट हो गई। मुआवज़े की मांग कर रहे हैं।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Agriculture",
    urgency: "High",
    issue_summary: "Flood destroyed fishermen boats in Majuli eliminating their livelihood with no compensation.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Majuli",
    district_hi: "माजुली",
    lok_sabha_en: "Jorhat",
    lok_sabha_hi: "जोरहाट",
    village: "Missamari Majuli",
    panchayat: "Missamari Gaon Panchayat",
    police_station: "Majuli",
    pincode: "785106",
    latitude: 26.9678,
    longitude: 94.3123,
    anonymous: false,
    name: "Biju Mising",
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "flood_crop_compensation",
    theme_name: "Flood Livelihood Loss — No Compensation",
    formatted_tracking_id: "JA-2026-MOCK0035",
    timestamp: hoursAgo(2 * 24 + 7),
    is_mock: true
  },

  // COMPLAINTS 36-40: KAMRUP METRO (URBAN GUWAHATI ISSUES)
  {
    text_original: "গুৱাহাটীৰ যানজঁট সমস্যা অসহ্য হৈ পৰিছে। ৰাস্তা কম, গাড়ী বেছি। মেট্ৰ' ৰেইলৰ কাম কেতিয়া শেষ হ'ব?",
    text_english: "Guwahati traffic congestion has become unbearable. Roads less, vehicles more. When will metro rail work be completed?",
    text_hindi: "गुवाहाटी में यातायात जाम असहनीय हो गया है। सड़क कम, गाड़ी ज़्यादा। मेट्रो रेल का काम कब पूरा होगा?",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Roads",
    urgency: "Medium",
    issue_summary: "Unbearable traffic congestion in Guwahati with metro rail construction delayed.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Kamrup Metropolitan",
    district_hi: "कामरूप महानगर",
    lok_sabha_en: "Guwahati",
    lok_sabha_hi: "गुवाहाटी",
    village: "Guwahati City",
    panchayat: "Guwahati Municipal Corporation",
    police_station: "Dispur",
    pincode: "781005",
    latitude: 26.1445,
    longitude: 91.7362,
    anonymous: false,
    name: "Ranjit Borah",
    phone: "9854234567",
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "guwahati_urban_infrastructure",
    theme_name: "Guwahati Urban Infrastructure",
    formatted_tracking_id: "JA-2026-MOCK0036",
    timestamp: hoursAgo(4 * 24 + 17),
    is_mock: true
  },
  {
    text_original: "গুৱাহাটীত বানপানীৰ সমস্যা বাঢ়িছে। নলা-নৰ্দমা বন্ধ। এঘণ্টা বৰষুণত ৰাস্তাত হাঁটু পানী।",
    text_english: "Flooding problem increasing in Guwahati. Drains blocked. Knee-deep water on roads after one hour of rain.",
    text_hindi: "गुवाहाटी में बाढ़ की समस्या बढ़ रही है। नालियाँ बंद हैं। एक घंटे की बारिश में सड़क पर घुटने तक पानी।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Sanitation/Waste",
    urgency: "High",
    issue_summary: "Blocked drains causing knee-deep flooding on Guwahati roads after just one hour of rain.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Kamrup Metropolitan",
    district_hi: "कामरूप महानगर",
    lok_sabha_en: "Guwahati",
    lok_sabha_hi: "गुवाहाटी",
    village: "Bhangagarh",
    panchayat: "Guwahati Municipal Corporation",
    police_station: "Bhangagarh",
    pincode: "781032",
    latitude: 26.1678,
    longitude: 91.7567,
    anonymous: false,
    name: "Pompi Devi",
    phone: null,
    photo_url: "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=400",
    photo_analysis: {
      what_is_shown: "Urban street completely flooded with knee-deep water, vehicles and pedestrians stranded",
      infrastructure_type: "Road",
      damage_visible: true,
      damage_description: "Severe urban flooding with blocked drainage causing road submersion",
      severity_from_photo: "High",
      severity_reasoning: "Urban flooding causing significant disruption to daily life and commerce",
      safety_concern: true,
      safety_detail: "Electrical hazard from submerged infrastructure and drowning risk in drainage pits",
      category_confirmed: false,
      category_suggested: "Sanitation/Waste",
      estimated_affected_area: "Block",
      flood_related: true,
      actionable_insight: "GMC drainage desilting emergency programme required before next monsoon rainfall",
      confidence: 0.89,
      analyzed_at: hoursAgo(3 * 24),
      analysis_failed: false
    },
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "photo_analysis",
    safety_flagged: true,
    theme_id: "guwahati_flooding",
    theme_name: "Urban Flooding — Guwahati",
    formatted_tracking_id: "JA-2026-MOCK0037",
    timestamp: hoursAgo(3 * 24 + 6),
    is_mock: true
  },
  {
    text_original: "গুৱাহাটীৰ চৰকাৰী চিকিৎসালয়ত বেড নাই। ৰোগী মজিয়াত শুই আছে। ব্যক্তিগত চিকিৎসালয়ত টকা নাই।",
    text_english: "No beds available in Guwahati government hospital. Patients lying on floor. Cannot afford private hospital.",
    text_hindi: "गुवाहाटी सरकारी अस्पताल में बेड नहीं है। मरीज़ फर्श पर लेटे हैं। प्राइवेट अस्पताल का खर्च नहीं उठा सकते।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Healthcare",
    urgency: "Critical",
    issue_summary: "Government hospital beds full with patients on floor unable to afford private care.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Kamrup Metropolitan",
    district_hi: "कामरूप महानगर",
    lok_sabha_en: "Guwahati",
    lok_sabha_hi: "गुवाहाटी",
    village: "Khanapara",
    panchayat: "Guwahati Municipal Corporation",
    police_station: "Khanapara",
    pincode: "781022",
    latitude: 26.1123,
    longitude: 91.8234,
    anonymous: true,
    name: null,
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: true,
    theme_id: "urban_healthcare_crisis",
    theme_name: "Urban Healthcare Capacity — Guwahati",
    formatted_tracking_id: "JA-2026-MOCK0038",
    timestamp: hoursAgo(2 * 24 + 8),
    is_mock: true
  },
  {
    text_original: "গুৱাহাটীত বৰ্জ্য পদাৰ্থ সংগ্ৰহ ঠিকমতে হোৱা নাই। ডাষ্টবিন উপচি পৰিছে। গোন্ধ আৰু ৰোগৰ ভয়।",
    text_english: "Waste collection not happening properly in Guwahati. Dustbins overflowing. Fear of smell and disease.",
    text_hindi: "गुवाहाटी में कचरा संग्रहण ठीक से नहीं हो रहा। डस्टबिन भरे पड़े हैं। बदबू और बीमारी का डर।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Sanitation/Waste",
    urgency: "Medium",
    issue_summary: "Overflowing dustbins in Guwahati due to poor waste collection creating health hazard.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Kamrup Metropolitan",
    district_hi: "कामरूप महानगर",
    lok_sabha_en: "Guwahati",
    lok_sabha_hi: "गुवाहाटी",
    village: "Zoo Road",
    panchayat: "Guwahati Municipal Corporation",
    police_station: "Zoo Road",
    pincode: "781005",
    latitude: 26.1789,
    longitude: 91.7456,
    anonymous: false,
    name: "Anita Sharma",
    phone: "9435345678",
    photo_url: null,
    photo_analysis: null,
    status: "resolved",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "urban_sanitation_guwahati",
    theme_name: "Urban Sanitation — Guwahati",
    formatted_tracking_id: "JA-2026-MOCK0039",
    timestamp: hoursAgo(1 * 24 + 16),
    is_mock: true
  },
  {
    text_original: "গুৱাহাটীৰ বিদ্যালয়ত শিক্ষকৰ অভাৱ। বিজ্ঞান আৰু গণিতৰ শিক্ষক নাই। ছাত্ৰৰ ভৱিষ্যত অন্ধকাৰ।",
    text_english: "Shortage of teachers in Guwahati schools. No science and maths teachers. Students' future is dark.",
    text_hindi: "गुवाहाटी स्कूलों में शिक्षकों की कमी है। विज्ञान और गणित के शिक्षक नहीं हैं। छात्रों का भविष्य अंधकार में।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Education/Schools",
    urgency: "High",
    issue_summary: "Shortage of science and maths teachers in Guwahati schools threatening student futures.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Kamrup Metropolitan",
    district_hi: "कामरूप महानगर",
    lok_sabha_en: "Guwahati",
    lok_sabha_hi: "गुवाहाटी",
    village: "Jalukbari",
    panchayat: "Guwahati Municipal Corporation",
    police_station: "Jalukbari",
    pincode: "781013",
    latitude: 26.1456,
    longitude: 91.6789,
    anonymous: false,
    name: "Kalyani Bora",
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "teacher_shortage_assam",
    theme_name: "Teacher Shortage — Assam Schools",
    formatted_tracking_id: "JA-2026-MOCK0040",
    timestamp: hoursAgo(6),
    is_mock: true
  },

  // COMPLAINTS 41-50: MIXED DISTRICTS (MORIGAON, LAKHIMPUR, JORHAT, SIBSAGAR, GOALPARA)
  {
    text_original: "মৰিগাঁৱত পোহৰৰ খুঁটা বানপানীত উলটি গৈছে। বিদ্যুৎ তাঁৰ পানীত পৰিছে। অতি বিপদজনক।",
    text_english: "Electric poles overturned by flood in Morigaon. Electric wires fallen in water. Very dangerous.",
    text_hindi: "मोरीगाँव में बाढ़ से बिजली के खंभे पलट गए हैं। बिजली के तार पानी में गिरे हैं। बहुत खतरनाक।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Electricity",
    urgency: "Critical",
    issue_summary: "Flood-toppled electric poles with live wires in floodwater creating life-threatening hazard.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Morigaon",
    district_hi: "मोरीगाँव",
    lok_sabha_en: "Nagaon",
    lok_sabha_hi: "नागाँव",
    village: "Jagiroad",
    panchayat: "Jagiroad Gaon Panchayat",
    police_station: "Jagiroad",
    pincode: "782410",
    latitude: 26.2678,
    longitude: 92.3456,
    anonymous: false,
    name: "Hemanta Das",
    phone: "8876123456",
    photo_url: null,
    photo_analysis: null,
    status: "escalated",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: true,
    theme_id: "flood_electrical_hazard",
    theme_name: "Flood Electrical Hazard — Morigaon",
    formatted_tracking_id: "JA-2026-MOCK0041",
    timestamp: hoursAgo(5 * 24 + 6),
    is_mock: true
  },
  {
    text_original: "লখিমপুৰত পথালি বানে ধান খেতি নষ্ট কৰিছে। কিষাণ ক্ৰেডিট কাৰ্ড ঋণ শোধ কৰিব নোৱাৰিম। বেংকে চাপ দিছে।",
    text_english: "Floods destroyed paddy crop in Lakhimpur. Cannot repay Kisan Credit Card loan. Bank is pressuring.",
    text_hindi: "लखीमपुर में बाढ़ ने धान की फसल नष्ट कर दी। किसान क्रेडिट कार्ड ऋण चुका नहीं पाऊंगा। बैंक दबाव दे रहा है।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Agriculture",
    urgency: "High",
    issue_summary: "Flood destroyed paddy crop leaving farmer unable to repay Kisan Credit Card loan under bank pressure.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Lakhimpur",
    district_hi: "लखीमपुर",
    lok_sabha_en: "Lakhimpur",
    lok_sabha_hi: "लखीमपुर",
    village: "North Lakhimpur",
    panchayat: "North Lakhimpur Gaon Panchayat",
    police_station: "North Lakhimpur",
    pincode: "787001",
    latitude: 27.2345,
    longitude: 94.1012,
    anonymous: false,
    name: "Prabin Gogoi",
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "flood_crop_compensation",
    theme_name: "Flood Crop Loss — No Compensation",
    formatted_tracking_id: "JA-2026-MOCK0042",
    timestamp: hoursAgo(4 * 24 + 13),
    is_mock: true
  },
  {
    text_original: "জোৰহাটৰ চাহ গৱেষণা কেন্দ্ৰৰ সুবিধা সৰু খেতিয়কে নাপায়। কেৱল ডাঙৰ বাগিচাই পায়। বৈষম্য দূৰ কৰক।",
    text_english: "Small farmers in Jorhat do not get benefits from Tea Research Centre. Only big gardens get it. Remove this inequality.",
    text_hindi: "जोरहाट में छोटे किसानों को चाय अनुसंधान केंद्र का लाभ नहीं मिलता। केवल बड़े बागान को मिलता है। यह असमानता दूर करें।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Agriculture",
    urgency: "Medium",
    issue_summary: "Small tea farmers excluded from Tea Research Centre benefits available only to large gardens.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Jorhat",
    district_hi: "जोरहाट",
    lok_sabha_en: "Jorhat",
    lok_sabha_hi: "जोरहाट",
    village: "Teok",
    panchayat: "Teok Gaon Panchayat",
    police_station: "Teok",
    pincode: "785631",
    latitude: 26.6789,
    longitude: 94.5678,
    anonymous: false,
    name: "Mridul Bora",
    phone: "9706789012",
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "small_farmer_exclusion",
    theme_name: "Small Farmer Scheme Exclusion",
    formatted_tracking_id: "JA-2026-MOCK0043",
    timestamp: hoursAgo(3 * 24 + 14),
    is_mock: true
  },
  {
    text_original: "শিৱসাগৰৰ তেল নিষ্কাশনৰ কাৰণে আমাৰ মাটি প্ৰদূষিত হৈছে। খেতি হোৱা নাই। OIL কোম্পানীয়ে ক্ষতিপূৰণ দিয়া নাই।",
    text_english: "Our land polluted due to oil extraction in Sibsagar. No farming possible. OIL company has not given compensation.",
    text_hindi: "सिबसागर में तेल निष्कर्षण से हमारी जमीन प्रदूषित हो गई है। खेती नहीं हो सकती। OIL कंपनी ने मुआवजा नहीं दिया।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Agriculture",
    urgency: "High",
    issue_summary: "Land contaminated by OIL company extraction in Sibsagar preventing farming with no compensation.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Sibsagar",
    district_hi: "शिवसागर",
    lok_sabha_en: "Jorhat",
    lok_sabha_hi: "जोरहाट",
    village: "Nazira",
    panchayat: "Nazira Gaon Panchayat",
    police_station: "Nazira",
    pincode: "785685",
    latitude: 26.9123,
    longitude: 94.7345,
    anonymous: false,
    name: "Bipin Hazarika",
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "industrial_pollution_assam",
    theme_name: "Industrial Pollution — Sibsagar",
    formatted_tracking_id: "JA-2026-MOCK0044",
    timestamp: hoursAgo(2 * 24 + 15),
    is_mock: true
  },
  {
    text_original: "গোৱালপাৰাত হস্তীৰ আক্ৰমণত খেতি নষ্ট হৈছে। বনবিভাগে সহায় কৰা নাই। ৰাতি ঘৰৰ পৰা ওলাব পৰা নাই।",
    text_english: "Crops destroyed by elephant attacks in Goalpara. Forest department has not helped. Cannot come out of house at night.",
    text_hindi: "गोलपारा में हाथी के हमलों से फसल नष्ट हो गई है। वन विभाग ने मदद नहीं की। रात में घर से बाहर नहीं निकल सकते।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Agriculture",
    urgency: "High",
    issue_summary: "Elephant attacks destroying crops in Goalpara with no forest department intervention.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Goalpara",
    district_hi: "गोलपारा",
    lok_sabha_en: "Dhubri",
    lok_sabha_hi: "धुबरी",
    village: "Lakhipur",
    panchayat: "Lakhipur Gaon Panchayat",
    police_station: "Lakhipur",
    pincode: "783131",
    latitude: 26.0456,
    longitude: 90.6789,
    anonymous: false,
    name: "Sanjib Koch",
    phone: "9435678901",
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: true,
    theme_id: "human_wildlife_conflict",
    theme_name: "Human-Wildlife Conflict — Goalpara",
    formatted_tracking_id: "JA-2026-MOCK0045",
    timestamp: hoursAgo(1 * 24 + 9),
    is_mock: true
  },
  {
    text_original: "গোৱালপাৰাৰ সীমান্ত এলেকাত পানীয় জলৰ সমস্যা আছে। গভীৰ নলকূপ বিকল হৈছে। মহিলাসকলে দূৰৈৰ পৰা পানী আনে।",
    text_english: "Drinking water problem in border areas of Goalpara. Deep tube wells broken. Women bring water from far away.",
    text_hindi: "गोलपारा के सीमावर्ती क्षेत्रों में पेयजल की समस्या है। गहरे नलकूप खराब हो गए हैं। महिलाएं दूर से पानी लाती हैं।",
    language_detected: "Assamese",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Water Supply",
    urgency: "High",
    issue_summary: "Broken deep tubewells in Goalpara border areas forcing women to travel far for water.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Goalpara",
    district_hi: "गोलपारा",
    lok_sabha_en: "Dhubri",
    lok_sabha_hi: "धुबरी",
    village: "Dudhnoi",
    panchayat: "Dudhnoi Gaon Panchayat",
    police_station: "Dudhnoi",
    pincode: "783124",
    latitude: 26.0789,
    longitude: 90.9012,
    anonymous: true,
    name: null,
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "water_contamination_darrang",
    theme_name: "Water Access Crisis — Assam",
    formatted_tracking_id: "JA-2026-MOCK0046",
    timestamp: hoursAgo(18),
    is_mock: true
  },
  {
    text_original: "हमारे गाँव में प्राथमिक स्वास्थ्य केंद्र बंद है। ANM दीदी महीने में एक बार आती है। बच्चों को टीका नहीं लग रहा।",
    text_english: "Primary health centre in our village is closed. ANM nurse comes once a month. Children not getting vaccinated.",
    text_hindi: "हमारे गाँव में प्राथमिक स्वास्थ्य केंद्र बंद है। ANM दीदी महीने में एक बार आती है। बच्चों को टीका नहीं लग रहा।",
    language_detected: "Hindi",
    language_native: "हिन्दी",
    language_script: "Devanagari",
    category: "Healthcare",
    urgency: "High",
    issue_summary: "PHC closed with ANM visiting only monthly leaving children unvaccinated in Lakhimpur.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Lakhimpur",
    district_hi: "लखीमपुर",
    lok_sabha_en: "Lakhimpur",
    lok_sabha_hi: "लखीमपुर",
    village: "Dhakuakhana",
    panchayat: "Dhakuakhana Gaon Panchayat",
    police_station: "Dhakuakhana",
    pincode: "787055",
    latitude: 27.3678,
    longitude: 94.3234,
    anonymous: false,
    name: "Savita Devi",
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "phc_closure_assam",
    theme_name: "PHC Closure — Rural Assam",
    formatted_tracking_id: "JA-2026-MOCK0047",
    timestamp: hoursAgo(14),
    is_mock: true
  },
  {
    text_original: "আমাদের গ্রামের রাস্তা বর্ষায় কাদায় ভরে যায়। স্কুলের বাচ্চারা পড়ে যায়। বৃদ্ধরা হাঁটতে পারেন না।",
    text_english: "Village road fills with mud in rainy season. School children fall down. Elderly cannot walk.",
    text_hindi: "बरसात में गाँव की सड़क कीचड़ से भर जाती है। स्कूली बच्चे गिरते हैं। बुजुर्ग चल नहीं सकते।",
    language_detected: "Bengali",
    language_native: "বাংলা",
    language_script: "Bengali",
    category: "Roads",
    urgency: "Medium",
    issue_summary: "Unpaved village road becomes dangerously muddy in monsoon affecting children and elderly.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Morigaon",
    district_hi: "मोरीगाँव",
    lok_sabha_en: "Nagaon",
    lok_sabha_hi: "नागाँव",
    village: "Laharighat",
    panchayat: "Laharighat Gaon Panchayat",
    police_station: "Laharighat",
    pincode: "782127",
    latitude: 26.3456,
    longitude: 92.2345,
    anonymous: false,
    name: "Rokeya Begum",
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "flood_road_damage_darrang",
    theme_name: "Monsoon Road Damage — Rural Assam",
    formatted_tracking_id: "JA-2026-MOCK0048",
    timestamp: hoursAgo(10),
    is_mock: true
  },
  {
    text_original: "Jorhat airport road is in terrible condition. Important for tourism and connectivity. No repair work done in 2 years.",
    text_english: "Jorhat airport road is in terrible condition. Important for tourism and connectivity. No repair work done in 2 years.",
    text_hindi: "जोरहाट हवाईअड्डा सड़क बहुत खराब स्थिति में है। पर्यटन और कनेक्टिविटी के लिए महत्वपूर्ण है। 2 साल से मरम्मत नहीं हुई।",
    language_detected: "English",
    language_native: "English",
    language_script: "Latin",
    category: "Roads",
    urgency: "Medium",
    issue_summary: "Jorhat airport road unrepaired for 2 years affecting tourism and regional connectivity.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Jorhat",
    district_hi: "जोरहाट",
    lok_sabha_en: "Jorhat",
    lok_sabha_hi: "जोरहाट",
    village: "Jorhat Town",
    panchayat: "Jorhat Municipal Board",
    police_station: "Jorhat",
    pincode: "785001",
    latitude: 26.7509,
    longitude: 94.2037,
    anonymous: false,
    name: "Manas Gogoi",
    phone: "9435901234",
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "road_damage_dibrugarh",
    theme_name: "Road Damage — Upper Assam",
    formatted_tracking_id: "JA-2026-MOCK0049",
    timestamp: hoursAgo(4),
    is_mock: true
  },
  {
    text_original: "শিৱসাগৰৰ ঐতিহাসিক পুখুৰীবোৰ প্ৰদূষিত হৈছে। পৰ্যটন নষ্ট হৈছে। স্থানীয় লোকে নহা কৰে কিন্তু পানী যোগান ধৰা নহয়।",
    text_english: "Historic ponds of Sibsagar are polluted. Tourism destroyed. Local people do not litter but water supply not managed.",
    text_hindi: "शिवसागर के ऐतिहासिक तालाब प्रदूषित हो गए हैं। पर्यटन नष्ट हो रहा है। स्थानीय लोग गंदगी नहीं करते लेकिन जल प्रबंधन नहीं है।",
    language_detected: "Historic ponds of Sibsagar are polluted. Tourism destroyed. Local people do not litter but water supply not managed.",
    language_native: "অসমীয়া",
    language_script: "Bengali",
    category: "Sanitation/Waste",
    urgency: "Medium",
    issue_summary: "Historic Sibsagar ponds polluted destroying tourism potential despite local community care.",
    state_en: "Assam",
    state_hi: "असम",
    district_en: "Sibsagar",
    district_hi: "शिवसागर",
    lok_sabha_en: "Jorhat",
    lok_sabha_hi: "जोरहाट",
    village: "Sibsagar Town",
    panchayat: "Sibsagar Municipal Board",
    police_station: "Sibsagar",
    pincode: "785640",
    latitude: 26.9856,
    longitude: 94.6342,
    anonymous: false,
    name: "Tarun Phukan",
    phone: null,
    photo_url: null,
    photo_analysis: null,
    status: "pending",
    moderation_flag: "clean",
    urgency_source: "keyword_matching",
    safety_flagged: false,
    theme_id: "heritage_pollution_sibsagar",
    theme_name: "Heritage Pollution — Sibsagar",
    formatted_tracking_id: "JA-2026-MOCK0050",
    timestamp: hoursAgo(2),
    is_mock: true
  }
];
